# Generated by Django 4.2.2 on 2023-11-01 13:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='attendee',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('isCash', models.BooleanField()),
                ('hashVal', models.CharField(max_length=64)),
                ('isVip', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.timedelta(days=19662, seconds=70084, microseconds=625875))),
                ('handledBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
