# Generated by Django 4.2.2 on 2023-11-01 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(default=datetime.timedelta(days=19662, seconds=70124, microseconds=434247)),
        ),
    ]
