# Generated by Django 4.2.2 on 2023-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(default='2023-11-02 01:27:28.190747+05:30'),
        ),
    ]
