# Generated by Django 4.2.2 on 2023-10-14 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0002_attendee_handledby'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='hashVal',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
