# Generated by Django 4.2.2 on 2023-11-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0002_alter_attendee_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='created_datetime',
            field=models.DateTimeField(),
        ),
    ]
