# Generated by Django 4.2.2 on 2023-11-01 14:03

from django.db import migrations, models
import ticket_generation.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0002_alter_attendee_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(default=ticket_generation.models.current_time),
        ),
    ]
