# Generated by Django 4.2.2 on 2023-11-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0003_alter_attendee_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(default='2023-11-02 01:28:14.241094+05:30'),
        ),
    ]
