# Generated by Django 4.2.2 on 2023-10-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0003_attendee_hashval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='hashVal',
            field=models.CharField(max_length=64),
        ),
    ]
