# Generated by Django 4.2.2 on 2023-11-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0003_alter_attendee_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
