# Generated by Django 4.2.2 on 2023-11-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0004_alter_attendee_id_alter_attendee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='mailid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
