# Generated by Django 4.2.2 on 2023-10-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0004_alter_attendee_hashval'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
