# Generated by Django 4.2.2 on 2023-11-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0005_attendee_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='verified',
            new_name='isVip',
        ),
    ]
