# Generated by Django 4.2.2 on 2023-11-01 13:42

from django.db import migrations
import django.utils.timezone
import ticket_generation.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_generation', '0006_rename_verified_attendee_isvip'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='created_at',
            field=ticket_generation.models.UTC530DateTimeField(default=django.utils.timezone.now),
        ),
    ]
